# Generated by Django 4.0.3 on 2022-03-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proto_books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookmark',
            new_name='BookmarkModel',
        ),
    ]
