# Generated by Django 4.0.3 on 2022-04-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proto_books', '0002_rename_bookmark_bookmarkmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkmodel',
            name='site_color',
            field=models.IntegerField(choices=[(1, 'red'), (2, 'blue'), (3, 'green'), (4, 'yellow'), (5, 'orange'), (6, 'black'), (7, 'gray'), (8, 'purple')], default=2),
        ),
        migrations.AddField(
            model_name='bookmarkmodel',
            name='site_memo',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
